### PR TITLE
fix : Rename and fix 'Low Profile' window

### PR DESCRIPTION
**Pull request by dockabernathy01**
Feature: Rename and fix  'Low Profile' window.

- Feature

Issue Number: 78

## What is the new behavior?

- I changed from 'Minimize'  to 'Low Profile'.
- I fixed the issues on 'Low Profile' window.
- I checked it on Windows .

### CODE REVIEW

**Comment by dockabernathy01** [comment]
@dacoaster , I renamed and fix 'Low Profile' window.
And I confirmed it on Windows.
There is a problem on my Mac. So I haven't checked on Mac.
Please merge after

**Comment by dacoaster** [comment]
@dockabernathy01 I tried it and the window was very large and had weird visual glitches when I took screenshots and such.  only the control panel bar should be shown without all of this extra black space
image

**Comment by dockabernathy01** [comment]
It works well on Windows, Linux, and Mac.
I have checked on all OS.
Please check and merge.

**Comment by dockabernathy01** [comment]
Hello @dacoaster . I have updated the code.
Please check and let me know.

**Pull request merged**
