### PR TITLE
implement new mindmap

### PR DESCRIPTION
**Pull request by dockabernathy01**
Implemented New Mindmap.

- Feature

## What is the new behavior?

- Add new Node component.
- Use dom-to-image to save the mindmap.

### CODE REVIEW

**Comment by dockabernathy01** [comment]
Hello @dacoaster.
I have implemented new mindmap. 
Please check and let me know.

**Comment by dacoaster** [comment]
@dockabernathy01 here are some issues to be fixed:

- When new nodes are created that have images in them, they are truncated due to the default node size but as soon as you move them and it redraws them, it fixes the issue
image-daed0
- When new nodes are created it often places them on top of other nodes so they need to be spaced out more by default
image-f6236
- A single click should only select the node, but it is opening the edit window
- We should disable the simple edit window that only has the title and status and just use the built in yattie edit windows
- When a new session is started and the mindmap is empty, we should display some sort of "Get started testing to build a testing tree" message instead of the empty workspace
- The default window size of the app should be larger so we don't have to scroll so much

**Comment by dacoaster** [comment]
@dockabernathy01 is this ready for testing again?

**Comment by dockabernathy01** [comment]
@dacoaster , Yes. it's ready.

**Comment by dockabernathy01** [comment]
@dacoaster , I have fixed the issues you mentioned.
Please check and let me know.

**Comment by dacoaster** [comment]
- When you close the app and open it on the mindmap workspace it draws all of the bubbles small and truncates the evidence pictures similar to what it was doing before

please just fix this in the next PR

**Comment by dacoaster** [comment]
@dockabernathy01 please see above

**Pull request merged**
